; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = micro_pro

[env:nano_old]
board = nanoatmega328
platform = atmelavr
framework = arduino
; build_flags =
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

[env:nano_new]
board = nanoatmega328new
platform = atmelavr
framework = arduino
; build_flags =
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

[env:micro_pro]
board = micro
platform = atmelavr
framework = arduino
; build_flags =
upload_port = COM17
monitor_port = COM17
monitor_speed = 115200
